'use client';
import {useEffect,useState} from 'react';
import {useParams,useSearchParams} from 'next/navigation';
import {useAppContext} from '@/context/app-context';
import {getFromCache,saveToCache} from '@/lib/offline-db';
import {serverReachable} from '@/lib/offline-session';
import {getCustomerLedgerAction} from '@/lib/operational-actions';
import {Button} from '@/components/ui/button';
import {PageHeader} from '@/components/page-header';
import Link from 'next/link';
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function CustomerDetailPage(){
 const {user,customers,sales,cashTransactions,isOffline}=useAppContext(),params=useParams(),query=useSearchParams();const id=query.get('id')??String(params.id??'');const [page,setPage]=useState(1),[data,setData]=useState<Awaited<ReturnType<typeof getCustomerLedgerAction>>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let cancelled=false;if(!user?.storeId)return;setBusy(true);setError('');(async()=>{
 const scope=user.uid+':'+user.storeId,key='ledger:'+id+':'+page;
 if(await serverReachable()){const r=await getCustomerLedgerAction(user.storeId!,id,page);await saveToCache(scope,key,r);return r;}
 const customer=customers.find(c=>c.id===id);if(!customer){const cached=await getFromCache<any>(scope,key);if(cached)return cached;throw new Error('Cliente não disponível neste dispositivo.');}
 const events:any[]=[...sales.filter(s=>s.customerId===id&&s.status!=='Cancelada').map(s=>({id:s.id,date:s.date,kind:s.status==='Pendente'?'Venda pendente':'Venda',description:s.customerName,amount:s.total,credit:s.paymentMethods.filter(p=>p.method==='Fiado').reduce((n,p)=>n+p.amount,0),points:Math.floor((s.total-s.paymentMethods.filter(p=>p.method==='Pontos').reduce((n,p)=>n+p.amount,0))*0.1)-s.paymentMethods.filter(p=>p.method==='Pontos').reduce((n,p)=>n+p.amount*10,0)})),...cashTransactions.filter(t=>t.customerId===id&&t.type==='Recebimento Fiado').map(t=>({id:t.id,date:t.date,kind:'Recebimento',description:t.description,amount:t.amount,credit:-t.amount,points:0}))].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
 const openingBalance=customer.balance-events.reduce((n,r)=>n+r.credit,0),openingPoints=(customer.loyaltyPoints??0)-events.reduce((n,r)=>n+r.points,0);let balance=openingBalance,points=openingPoints;
 const rows=events.map(row=>{balance+=row.credit;points+=row.points;return {...row,balance,pointBalance:points,total:events.length,openingBalance,openingPoints};});
 return {customer,rows:rows.slice((page-1)*50,page*50),total:rows.length,page,openingBalance,openingPoints} as any;
})().then(d=>{if(!cancelled)setData(d);}).catch(()=>{if(!cancelled)setError('Não foi possível carregar este cliente. Confira seu acesso e tente novamente.');}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[user?.storeId,id,page,revision,isOffline,customers,sales,cashTransactions]);
 return <div className="space-y-5"><Link className="underline" href="/dashboard/customers">Voltar aos clientes</Link><PageHeader title={data?.customer.name??'Extrato do cliente'} description="Compras, recebimentos, cancelamentos, fiado e pontos"/>{error&&<p role="alert">{error} <Button onClick={()=>setRevision(n=>n+1)}>Tentar novamente</Button></p>}{busy?<p role="status">Carregando extrato…</p>:data&&<><div className="grid gap-3 rounded border bg-background p-4 sm:grid-cols-3"><p>Saldo devedor: <strong>{money(data.customer.balance)}</strong></p><p>Limite: <strong>{money(data.customer.creditLimit)}</strong></p><p>Pontos: <strong>{data.customer.loyaltyPoints}</strong></p><p>{data.customer.phone}</p><p>{data.customer.email}</p></div><p className="text-sm text-muted-foreground">10 pontos equivalem a R$ 1 no pagamento. Cada compra gera a parte inteira de 10% do valor, descontado o resgate. Cancelamentos revertem o fiado e os pontos da venda. O valor total da compra e a alteração no fiado são mostrados separadamente.</p><p className="text-sm">Saldo anterior ao histórico disponível: {money(data.openingBalance)} · {data.openingPoints} pontos. Este saldo reconcilia registros antigos ou ajustes; os movimentos abaixo explicam o saldo atual.</p><div className="overflow-auto rounded border bg-background"><table className="w-full text-left text-sm"><thead><tr>{['Data','Movimento','Total','Alteração fiado','Saldo fiado','Pontos +/-','Saldo pontos'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{data.rows.map(row=><tr key={row.id} className="border-t"><td className="whitespace-nowrap p-3">{new Date(row.date).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</td><td className="p-3"><strong>{row.kind}</strong><p>{row.description}</p></td><td className="p-3">{money(row.amount)}</td><td className="p-3">{money(row.credit)}</td><td className="p-3">{money(row.balance)}</td><td className="p-3">{row.points}</td><td className="p-3">{row.pointBalance}</td></tr>)}</tbody></table>{!data.rows.length&&<p className="p-4">Nenhum movimento financeiro registrado.</p>}</div><div className="flex items-center gap-3"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(n=>n-1)}>Anterior</Button><span>{data.total} movimentos · página {page}</span><Button variant="outline" disabled={page*50>=data.total} onClick={()=>setPage(n=>n+1)}>Próxima</Button></div></>}</div>;
}
