'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { useAuth } from '@/context/app-context';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { newRequestId } from '@/lib/request-id';
import { printPickupTickets } from '@/lib/print-pickup-tickets';
import { getServiceDataAction,saveServiceTableAction,openServiceTabAction,addServiceItemAction,removeServiceItemAction,cancelServiceTabAction,closeServiceTabAction,issuePickupTicketsAction,purchasePickupTicketsAction,redeemPickupTicketAction,getServiceReportAction } from '@/lib/service-actions';
import type { PrintableTicket } from '@/components/service/ticket-print';
import type { Sale } from '@/lib/types';
const TicketPrint=dynamic(()=>import('@/components/service/ticket-print').then(m=>m.TicketPrint),{ssr:false});
const ReceiptDialog=dynamic(()=>import('@/components/sales/receipt-dialog').then(m=>m.ReceiptDialog),{ssr:false});
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const methods=['Dinheiro','Crédito','Débito','Pix'] as const;
type Method=typeof methods[number];
type Data=Awaited<ReturnType<typeof getServiceDataAction>>;
type Product=Data['products'][number];
type PaymentDraft=Record<Method,string>;
const emptyPayments:PaymentDraft={Dinheiro:'',Crédito:'',Débito:'',Pix:''};
type Checkout={kind:'mesa';tabId:string;total:number}|{kind:'fichas';product:Product;quantity:number;total:number;requestId:string};

export default function ServicePage() {
  const {user,reloadUser}=useAuth();const storeId=user?.storeId??'';
  const manager=user?.role==='Administrador'||user?.role==='Gerente';
  const [view,setView]=useState<'mesas'|'fichas'|'resumo'>('mesas');
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [search,setSearch]=useState(''),[query,setQuery]=useState('');const sequence=useRef(0);
  const [selectedId,setSelectedId]=useState(''),[tableName,setTableName]=useState(''),[opening,setOpening]=useState<Data['tables'][number]|null>(null),[customerName,setCustomerName]=useState('');
  const [product,setProduct]=useState<Product|null>(null),[quantity,setQuantity]=useState('1'),[sessionId,setSessionId]=useState('');
  const [saleId,setSaleId]=useState(''),[code,setCode]=useState(''),[tickets,setTickets]=useState<PrintableTicket[]>([]);
  const [receiptSale,setReceiptSale]=useState<Sale|null>(null),[receiptOpen,setReceiptOpen]=useState(false);
  const [checkout,setCheckout]=useState<Checkout|null>(null),[paymentDraft,setPaymentDraft]=useState<PaymentDraft>(emptyPayments),[pixConfirmed,setPixConfirmed]=useState(false);
  const [reversal,setReversal]=useState<{kind:'item'|'mesa';id:string}|null>(null),[reason,setReason]=useState('');
  const [from,setFrom]=useState(''),[to,setTo]=useState(''),[report,setReport]=useState<Awaited<ReturnType<typeof getServiceReportAction>>|null>(null);
  const itemRequest=useRef(''),purchaseRequest=useRef('');
  const load=useCallback(async()=>{
    const current=++sequence.current;if(!storeId){setLoading(false);return;}setLoading(true);
    try {const r=await getServiceDataAction(storeId,query);if(current===sequence.current){setData(r);setError('');}}
    catch(c){if(current===sequence.current){setData(null);setError(c instanceof Error?c.message:'Não foi possível carregar.');}}
    finally{if(current===sequence.current)setLoading(false);}
  },[storeId,query]);
  useEffect(()=>{void load();return()=>{sequence.current++;};},[load]);
  useEffect(()=>{const timer=setTimeout(()=>setQuery(search),300);return()=>clearTimeout(timer);},[search]);
  useEffect(()=>{const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());setFrom(today);setTo(today);},[]);
  useEffect(()=>{setSelectedId('');setProduct(null);setTickets([]);setReport(null);setCheckout(null);setSessionId('');setSaleId('');setReceiptSale(null);setReceiptOpen(false);itemRequest.current='';purchaseRequest.current='';},[storeId]);
  const run=async(operation:()=>Promise<unknown>,message:string)=>{
    setPending(true);setError('');setNotice('');
    try{await operation();setNotice(message);await load();return true;}
    catch(c){setError(c instanceof Error?c.message:'Não foi possível concluir.');return false;}
    finally{setPending(false);}
  };
  const selected=data?.tables.find(t=>t.id===selectedId),tab=selected?.tabs[0];
  const total=tab?.items.reduce((n,i)=>n+i.quantity*i.price,0)??0;
  const activeSession=data?.sessions.some(s=>s.id===sessionId)?sessionId:data?.sessions[0]?.id??'';
  const chooseProduct=(id:string)=>{setProduct(data?.products.find(p=>p.id===id)??null);itemRequest.current='';purchaseRequest.current='';};
  const setQty=(v:string)=>{setQuantity(v);itemRequest.current='';purchaseRequest.current='';};
  const startCheckout=(value:Checkout)=>{setCheckout(value);setPaymentDraft({...emptyPayments,Dinheiro:value.total.toFixed(2)});setPixConfirmed(false);setError('');};
  const confirmCheckout=async(e:React.FormEvent)=>{
    e.preventDefault();if(!checkout)return;
    const payments=methods.map(method=>({method,amount:Number(paymentDraft[method])})).filter(p=>p.amount>0);
    if(Number(paymentDraft.Pix)>0&&!pixConfirmed){setError('Confirme o recebimento do Pix antes de concluir.');return;}
    const done=await run(async()=>{
      if(checkout.kind==='mesa'){const sale=await closeServiceTabAction(storeId,{tabId:checkout.tabId,sessionId:activeSession,totalCents:Math.round(checkout.total*100),payments});setReceiptSale(sale as unknown as Sale);setSaleId(sale.id);setSelectedId('');}
      else{const result=await purchasePickupTicketsAction(storeId,{productId:checkout.product.id,expectedPrice:checkout.product.price,quantity:checkout.quantity,sessionId:activeSession,requestId:checkout.requestId,payments});setReceiptSale(result.sale as unknown as Sale);setTickets(result.tickets);setSaleId(result.sale.id);purchaseRequest.current='';}
    },checkout.kind==='mesa'?'Conta da mesa registrada no caixa.':'Venda registrada; fichas prontas para imprimir.');
    if(done){setCheckout(null);setReceiptOpen(true);}
  };
  const addItem=async(e:React.FormEvent)=>{e.preventDefault();if(!tab||!product)return;itemRequest.current||=newRequestId();const done=await run(()=>addServiceItemAction(storeId,{tabId:tab.id,productId:product.id,quantity:Number(quantity),expectedPrice:tab.items.find(i=>i.productId===product.id)?.price??product.price,requestId:itemRequest.current}),'Consumo lançado e estoque atualizado.');if(done)itemRequest.current='';};
  const emit=async()=>{await run(async()=>{setTickets(await issuePickupTicketsAction(storeId,saleId));},'Fichas prontas. A reimpressão mantém os mesmos códigos.');};
  const selectProduct=<label className="block text-sm">Produto<select className="mt-1 block w-full rounded border bg-background p-2" value={product?.id??''} onChange={e=>chooseProduct(e.target.value)} disabled={pending}><option value="">Selecione um produto</option>{data?.products.map(p=><option value={p.id} key={p.id}>{p.name} · {money(p.price)} · estoque {p.stock} {p.unit}</option>)}</select></label>;
  if(!storeId)return <p>Selecione uma loja para acessar este módulo.</p>;
  return <div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Mesas e fichas</h1><p className="text-sm text-muted-foreground">{user?.store?.name} · Consumo por mesa e retirada de produtos</p></div><Button variant="outline" disabled={loading||pending} onClick={()=>{void reloadUser();void load();}}>Atualizar</Button></header>
    <nav aria-label="Funções do módulo" className="flex gap-2">{(['mesas','fichas',...(manager?['resumo']:[])] as ('mesas'|'fichas'|'resumo')[]).map(v=><Button key={v} variant={view===v?'default':'outline'} onClick={()=>setView(v)}>{v==='mesas'?'Mesas':v==='fichas'?'Fichas de retirada':'Resumo do período'}</Button>)}</nav>
    {error&&<p role="alert" className="rounded border border-destructive bg-background p-3 text-destructive">{error}</p>}{notice&&<p role="status" className="rounded bg-emerald-50 p-3 text-emerald-800">{notice}</p>}
    {loading&&!data?<p role="status">Carregando…</p>:!data?<p>O acesso depende da liberação deste módulo para sua empresa.</p>:<>
      {view==='mesas'&&<div className="grid gap-6 xl:grid-cols-[1fr_1.2fr]"><section className="space-y-4">{manager&&<form className="flex items-end gap-2" onSubmit={async e=>{e.preventDefault();if(await run(()=>saveServiceTableAction(storeId,{name:tableName,active:true}),'Mesa cadastrada.'))setTableName('');}}><label className="flex-1 text-sm">Nome da mesa<Input placeholder="Mesa 01" required maxLength={60} value={tableName} onChange={e=>setTableName(e.target.value)} disabled={pending}/></label><Button disabled={pending} type="submit">Cadastrar</Button></form>}
        <div className="grid gap-3 sm:grid-cols-2">{data.tables.map(table=><article key={table.id} className={`rounded-xl border bg-background p-4 ${selectedId===table.id?'ring-2 ring-primary':''}`}><h2 className="font-semibold">{table.name}</h2><p className="my-2 text-sm">{!table.active?'Desativada':table.tabs.length?'Aberta · '+money(table.tabs[0].items.reduce((n,i)=>n+i.quantity*i.price,0)):'Livre'}</p>{table.tabs[0]?.customerName&&<p className="mb-2 text-sm text-muted-foreground">{table.tabs[0].customerName}</p>}<div className="flex flex-wrap gap-2">{table.active&&(table.tabs.length?<Button size="sm" disabled={pending} onClick={()=>setSelectedId(table.id)}>Ver conta</Button>:<Button size="sm" disabled={pending} onClick={()=>{setOpening(table);setCustomerName('');}}>Abrir mesa</Button>)}{manager&&!table.tabs.length&&<Button size="sm" variant="outline" disabled={pending} onClick={()=>void run(()=>saveServiceTableAction(storeId,{id:table.id,name:table.name,active:!table.active}),table.active?'Mesa desativada.':'Mesa reativada.')}>{table.active?'Desativar':'Reativar'}</Button>}</div></article>)}</div>{!data.tables.length&&<p className="rounded border bg-background p-6 text-sm">Cadastre as mesas da loja para começar.</p>}</section>
        <section className="rounded-xl border bg-background p-5">{!tab?<p className="text-sm text-muted-foreground">Abra uma mesa ou selecione uma conta para lançar o consumo.</p>:<><div className="flex items-start justify-between gap-2"><div><h2 className="text-xl font-semibold">{selected?.name}</h2><p className="text-sm text-muted-foreground">{tab.customerName||'Sem identificação'} · aberta em {new Date(tab.openedAt).toLocaleString('pt-BR')}</p></div><strong>{money(total)}</strong></div><form onSubmit={addItem} className="my-5 space-y-3"><label className="block text-sm">Buscar produto<Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome do produto"/></label>{selectProduct}<div className="flex items-end gap-2"><label className="flex-1 text-sm">Quantidade ({product?.unit??'unidades'})<Input type="number" step="any" min="0.001" max="10000" required value={quantity} onChange={e=>setQty(e.target.value)} disabled={pending}/></label><Button type="submit" disabled={pending||!product}>Lançar consumo</Button></div><p className="text-xs text-muted-foreground">O lançamento baixa o estoque. Ao fechar a mesa, o consumo é registrado como venda sem nova baixa.</p></form>
          <ul className="divide-y">{tab.items.map(item=><li key={item.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-medium">{item.productName}</p><p className="text-sm text-muted-foreground">{item.quantity} {item.unit} × {money(item.price)}</p></div><div className="text-right"><p>{money(item.quantity*item.price)}</p>{manager&&<button disabled={pending} className="text-xs text-destructive underline" onClick={()=>{setReversal({kind:'item',id:item.id});setReason('');}}>Estornar</button>}</div></li>)}</ul>{!tab.items.length&&<p className="py-4 text-sm">Nenhum consumo lançado.</p>}<div className="mt-4 flex flex-wrap gap-2"><Button disabled={pending||!tab.items.length||!activeSession} onClick={()=>startCheckout({kind:'mesa',tabId:tab.id,total})}>Fechar conta · {money(total)}</Button>{manager&&<Button variant="outline" disabled={pending} onClick={()=>{setReversal({kind:'mesa',id:tab.id});setReason('');}}>Cancelar conta</Button>}</div>{!activeSession&&<p className="mt-2 text-sm text-destructive">Abra o caixa para receber o pagamento.</p>}</>}</section></div>}
      {view==='fichas'&&<div className="grid gap-6 lg:grid-cols-2"><section className="space-y-4 rounded-xl border bg-background p-5"><h2 className="text-lg font-semibold">Vender fichas</h2><label className="block text-sm">Buscar produto<Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome do produto"/></label>{selectProduct}<label className="block text-sm">Quantidade de fichas<Input type="number" min={1} max={200} step={1} value={quantity} onChange={e=>setQty(e.target.value)}/></label><Button disabled={pending||!product||!activeSession||!Number.isInteger(Number(quantity))||Number(quantity)<1||Number(quantity)>200} onClick={()=>{if(product){purchaseRequest.current||=newRequestId();startCheckout({kind:'fichas',product,quantity:Number(quantity),total:Math.round(product.price*Number(quantity)*100)/100,requestId:purchaseRequest.current});}}}>Receber e emitir fichas{product?' · '+money(product.price*Number(quantity)):''}</Button><p className="text-xs text-muted-foreground">Uma ficha por unidade. O estoque baixa na venda; a retirada valida a ficha sem baixar novamente.</p><div className="border-t pt-4"><h3 className="font-medium">Emitir ou reimprimir de uma venda</h3><label className="mt-3 block text-sm">Vendas recentes<select className="mt-1 w-full rounded border p-2" value={data.sales.some(s=>s.id===saleId)?saleId:''} onChange={e=>setSaleId(e.target.value)}><option value="">Selecione a venda</option>{data.sales.map(s=><option value={s.id} key={s.id}>{new Date(s.date).toLocaleString('pt-BR')} · {money(s.total)} · #{s.id.slice(0,8)}</option>)}</select></label><label className="mt-3 block text-sm">ID completo da venda<Input value={saleId} onChange={e=>setSaleId(e.target.value)} placeholder="ID da venda, inclusive para vendas anteriores"/></label><Button variant="outline" className="mt-3" disabled={pending||!saleId} onClick={()=>void emit()}>Preparar fichas</Button></div></section>
        <section className="space-y-4 rounded-xl border bg-background p-5"><h2 className="text-lg font-semibold">Confirmar retirada</h2><form onSubmit={async e=>{e.preventDefault();await run(async()=>{const name=await redeemPickupTicketAction(storeId,code);setCode('');setNotice('Retirada registrada: '+name);},'Retirada registrada.');}} className="space-y-3"><label className="block text-sm">Código da ficha<Input required value={code} onChange={e=>setCode(e.target.value)} placeholder="F-…" autoComplete="off" disabled={pending}/></label><Button type="submit" disabled={pending||!code}>Confirmar retirada</Button></form><p className="text-xs text-muted-foreground">Use o código impresso ou um leitor de código de barras. Fichas já utilizadas e vendas canceladas são recusadas.</p><h3 className="border-t pt-4 font-medium">Últimas fichas</h3><ul className="max-h-96 divide-y overflow-auto">{data.tickets.map(ticket=><li className="py-3 text-sm" key={ticket.id}><p>{ticket.productName} · {ticket.status}</p><code className="text-xs">{ticket.code}</code></li>)}</ul></section></div>}
      {view==='resumo'&&manager&&<section className="space-y-4 rounded-xl border bg-background p-5"><h2 className="text-lg font-semibold">Vendas e movimentação da loja</h2><form className="flex flex-wrap items-end gap-3" onSubmit={async e=>{e.preventDefault();await run(async()=>setReport(await getServiceReportAction(storeId,from,to)),'Resumo atualizado.');}}><label className="text-sm">De<Input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">Até<Input type="date" required value={to} onChange={e=>setTo(e.target.value)}/></label><Button type="submit" disabled={pending}>Consultar</Button></form><p className="text-sm text-muted-foreground">Inclui as vendas concluídas da loja, inclusive o PDV. Mesas abertas ainda não são vendas. Período de até 31 dias.</p>{report&&<div className="grid gap-3 sm:grid-cols-3">{[['Vendas',String(report.count)],['Total vendido',money(report.total)],...Object.entries(report.payments).map(([k,v])=>[k,money(v)]),['Sangrias',money(report.withdrawals)],['Despesas',money(report.expenses)]].map(([label,value])=><div key={label} className="rounded border p-4"><p className="text-sm text-muted-foreground">{label}</p><strong>{value}</strong></div>)}</div>}</section>}
    </>}
    {tickets.length>0&&<section className="rounded-xl border bg-background p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">{tickets.length} fichas preparadas</h2><Button onClick={()=>{try{printPickupTickets();}catch(e){setError(e instanceof Error?e.message:'Não foi possível imprimir.');}}}>Imprimir fichas</Button></div><p className="mt-2 text-sm text-muted-foreground">Os códigos permanecem iguais nas reimpressões. {tickets.filter(t=>t.status!=='Pendente').length} já utilizadas.</p><ul className="mt-3 max-h-48 overflow-auto text-sm">{tickets.map(t=><li key={t.id}>{t.productName} · {t.code} · {t.status}</li>)}</ul></section>}
    <Dialog open={!!opening} onOpenChange={v=>{if(!v&&!pending)setOpening(null);}}><DialogContent><DialogHeader><DialogTitle>Abrir {opening?.name}</DialogTitle><DialogDescription>Os consumos serão acumulados na conta desta mesa.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(!opening)return;const table=opening;if(await run(()=>openServiceTabAction(storeId,table.id,customerName),'Mesa aberta.')){setOpening(null);setSelectedId(table.id);}}}><label className="block text-sm">Identificação do cliente (opcional)<Input value={customerName} maxLength={100} onChange={e=>setCustomerName(e.target.value)}/></label><Button type="submit" disabled={pending}>Abrir mesa</Button></form></DialogContent></Dialog>
    <Dialog open={!!checkout} onOpenChange={v=>{if(!v&&!pending)setCheckout(null);}}><DialogContent><DialogHeader><DialogTitle>{checkout?.kind==='mesa'?'Fechar conta da mesa':'Receber e emitir fichas'}</DialogTitle><DialogDescription>Total: {money(checkout?.total??0)}. Informe os valores recebidos. Troco somente em dinheiro.</DialogDescription></DialogHeader><form onSubmit={confirmCheckout} className="space-y-4"><label className="block text-sm">Caixa<select className="mt-1 w-full rounded border p-2" value={activeSession} onChange={e=>setSessionId(e.target.value)}>{data?.sessions.map(s=><option key={s.id} value={s.id}>{s.openedByName} · #{s.id.slice(0,8)}</option>)}</select></label><div className="grid grid-cols-2 gap-3">{methods.map(method=><label className="text-sm" key={method}>{method}<Input type="number" step="0.01" min="0" max="1000000" value={paymentDraft[method]} onChange={e=>setPaymentDraft(p=>({...p,[method]:e.target.value}))} disabled={pending}/><button type="button" className="mt-1 text-xs underline" disabled={pending} onClick={()=>setPaymentDraft({...emptyPayments,[method]:(checkout?.total??0).toFixed(2)})}>Total em {method.toLowerCase()}</button></label>)}</div>{Number(paymentDraft.Pix)>0&&<label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={pixConfirmed} onChange={e=>setPixConfirmed(e.target.checked)} required/>Conferi o recebimento do Pix na conta da loja. A confirmação é manual.</label>}{error&&<p role="alert" className="text-destructive">{error}</p>}<Button type="submit" disabled={pending||!activeSession}>{pending?'Registrando…':'Confirmar pagamento'}</Button></form></DialogContent></Dialog>
    <Dialog open={!!reversal} onOpenChange={v=>{if(!v&&!pending)setReversal(null);}}><DialogContent><DialogHeader><DialogTitle>{reversal?.kind==='mesa'?'Cancelar conta da mesa':'Estornar consumo'}</DialogTitle><DialogDescription>O estoque será devolvido e o motivo ficará registrado na auditoria.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(!reversal)return;if(await run(()=>reversal.kind==='mesa'?cancelServiceTabAction(storeId,reversal.id,reason):removeServiceItemAction(storeId,reversal.id,reason),'Estorno registrado e estoque devolvido.'))setReversal(null);}}><label className="block text-sm">Motivo<Input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={pending} type="submit">Confirmar estorno</Button></form></DialogContent></Dialog>
    {receiptSale&&<><Button variant="outline" onClick={()=>setReceiptOpen(true)}>Ver recibo da última venda</Button><ReceiptDialog sale={receiptSale} open={receiptOpen} onOpenChange={setReceiptOpen}/></>}
    {!!user?.store&&tickets.length>0&&<TicketPrint tickets={tickets} store={user.store}/>}
  </div>;
}
