'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {useAppContext} from '@/context/app-context';
import {searchStoreAction} from '@/lib/operational-actions';
import {Input} from '@/components/ui/input';
export function GlobalSearch(){
 const {user,products,customers,sales,isOffline}=useAppContext(),router=useRouter();const [query,setQuery]=useState(''),[results,setResults]=useState<Awaited<ReturnType<typeof searchStoreAction>>>([]),[selected,setSelected]=useState(0),[state,setState]=useState(''),[open,setOpen]=useState(false);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{let cancelled=false;setResults([]);setSelected(0);if(query.trim().length<2){setState('');return;}setState('Buscando…');const timer=setTimeout(()=>{(async()=>{
 if(!isOffline)return searchStoreAction(query,user?.storeId??'');
 const q=query.trim().toLocaleLowerCase(),match=(row:any)=>Object.values(row).some(v=>typeof v==='string'&&v.toLocaleLowerCase().includes(q));
 return [...products.filter(match).slice(0,6).map(p=>({id:p.id,type:'Produtos',label:p.name,url:'/dashboard/products?search='+p.id})),...customers.filter(match).slice(0,6).map(c=>({id:c.id,type:'Clientes',label:c.name,url:'/dashboard/customers/detail?id='+c.id})),...sales.filter(match).slice(0,6).map(s=>({id:s.id,type:'Vendas',label:s.customerName+' · R$ '+s.total.toFixed(2),url:'/dashboard/sales?search='+s.id}))];
})().then(rows=>{if(!cancelled){setResults(rows);setState(rows.length?'':'Nenhum resultado nesta loja.');}}).catch(()=>{if(!cancelled)setState('Não foi possível buscar. Tente novamente.');});},300);return()=>{cancelled=true;clearTimeout(timer);};},[query,user?.storeId,isOffline,products,customers,sales]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key==='k'){event.preventDefault();input.current?.focus();setOpen(true);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const navigate=(index:number)=>{const row=results[index];if(row){setOpen(false);setQuery('');if(isOffline)location.assign(row.url);else router.push(row.url);}};
 return <div className="relative w-full md:w-80"><Input ref={input} aria-label="Buscar produtos, clientes e vendas" aria-controls="global-search-results" aria-expanded={open} aria-activedescendant={open&&results[selected]?'search-'+selected:undefined} role="combobox" placeholder="Buscar… (Ctrl K)" value={query} onFocus={()=>setOpen(true)} onBlur={()=>setTimeout(()=>setOpen(false),150)} onChange={e=>{setQuery(e.target.value);setOpen(true);}} onKeyDown={e=>{if(e.key==='Escape')setOpen(false);if(e.key==='ArrowDown'){e.preventDefault();setSelected(i=>Math.min(i+1,results.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setSelected(i=>Math.max(0,i-1));}if(e.key==='Enter'){e.preventDefault();navigate(selected);}}}/>{open&&query.trim().length>=2&&<div id="global-search-results" role="listbox" className="absolute right-0 top-full z-50 mt-2 max-h-96 w-full min-w-72 overflow-auto rounded-md border bg-background p-2 shadow-lg">{state&&<p role="status" className="p-2 text-sm">{state}</p>}{results.map((r,i)=><button id={'search-'+i} key={r.type+r.id} role="option" aria-selected={i===selected} className={'block w-full rounded p-2 text-left text-sm '+(i===selected?'bg-muted':'')} onMouseDown={e=>e.preventDefault()} onClick={()=>navigate(i)}><span className="block text-xs text-muted-foreground">{r.type}</span>{r.label}</button>)}</div>}</div>;
}
