'use client';
import { useState } from 'react';
import { useAppContext } from '@/context/app-context';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogTitle,DialogHeader,DialogDescription } from '@/components/ui/dialog';
export function OfflineSyncPanel(){
 const {offlineSync,syncOfflineSales,dataPage}=useAppContext();const [open,setOpen]=useState(false);
 return <><Button variant="outline" className="fixed bottom-3 right-3 z-40 shadow-md" onClick={()=>setOpen(true)}>{offlineSync.syncing?'Sincronizando…':`${offlineSync.items.length} venda(s) pendente(s)`}</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Sincronização de vendas</DialogTitle><DialogDescription>Vendas pendentes ainda não foram confirmadas pelo servidor. Cada reenvio conserva o identificador original.</DialogDescription></DialogHeader>{offlineSync.error&&<p role="alert">{offlineSync.error}</p>}<p className="text-xs text-muted-foreground">O catálogo offline armazena até 5.000 produtos e 5.000 clientes por conta e loja.</p>{dataPage.catalogLimited&&<p role="alert" className="text-amber-700">Esta loja ultrapassa o limite do catálogo local. Há registros fora do PDV carregado; revise o catálogo antes de operar offline.</p>}<p className="text-sm">Última verificação: {offlineSync.lastSync?new Date(offlineSync.lastSync).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Ainda não realizada'}</p><div className="max-h-80 space-y-3 overflow-auto">{!offlineSync.items.length?<p>Nenhuma venda pendente.</p>:offlineSync.items.map(item=><article key={item.id} className="rounded border p-3 text-sm"><p>{new Date(item.createdAt).toLocaleString('pt-BR')} · R$ {Number(item.saleData.total).toFixed(2)}</p><p className="break-all text-xs">{item.id}</p><p>{item.lastError||'Aguardando confirmação.'}</p><p className="text-muted-foreground">Tentativas: {item.attempts??0}. Se o caixa estiver fechado, solicite revisão à gerência. Não registre a mesma venda novamente.</p></article>)}</div><Button disabled={offlineSync.syncing} onClick={()=>void syncOfflineSales()}>Sincronizar agora</Button></DialogContent></Dialog></>;
}
