'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { UserNav } from '@/components/layout/user-nav';
import { Building2, Users, CreditCard, Receipt, ShieldCheck, LayoutDashboard, Layers, LogOut, Plus, Search, RefreshCw, ArrowUpRight, ChevronLeft, ChevronRight, X, CheckCircle2, AlertCircle } from 'lucide-react';
import { useAuth } from '@/context/app-context';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { getAdminDataAction, savePlanAction, saveSubscriptionAction, setSubscriptionStatusAction, resumeSubscriptionAction, recordInvoicePaymentAction, changeInvoiceStatusAction, manageUserAction, createPlatformUserAction, saveAdminStoreAction, setAdminStoreStatusAction, returnToAdminAction, syncBillingAction } from '@/lib/admin-actions';
import { createStoreAction, grantStoreAccessAction, selectStoreAction } from '@/lib/platform-actions';

const sections=[{id:'overview',label:'Visão geral',icon:LayoutDashboard},{id:'stores',label:'Lojas e empresas',icon:Building2},{id:'users',label:'Usuários e acessos',icon:Users},{id:'plans',label:'Planos',icon:Layers},{id:'subscriptions',label:'Assinaturas',icon:CreditCard},{id:'invoices',label:'Cobranças',icon:Receipt},{id:'audit',label:'Auditoria',icon:ShieldCheck}];
const money=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);
const date=(value?:string)=>value?new Date(value).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—';
type Data=Awaited<ReturnType<typeof getAdminDataAction>>;
type Row={id:string;uid:string;name:string;email:string;status:string;cnpj:string;address:string;phone:string;disabled:boolean;isPlatformAdmin:boolean;active:boolean;description:string;priceCents:number;maxUsers:number;planId:string;storeId:string;nextDue:string;notes:string;dueDate:string;amountCents:number;paidAt:string;paymentMethod:string;paymentReference:string;date:string;action:string;details:string;actorName:string;organization:{name:string};subscription?:{plan:{name:string};store:{name:string}};plan:{name:string};store:{name:string};memberships?:{store:{name:string;id:string};role:string;user:{email:string}}[];_count:{memberships:number;subscriptions:number}};
type Editor={kind:string;title:string;values:Record<string,string>};
type Field={key:string;label:string;type?:string;required?:boolean;options?:{value:string;label:string}[];min?:string;max?:string;readOnly?:boolean};
const roles=['Administrador','Gerente','Operador de Caixa','Estoquista'].map(value=>({value,label:value}));

function Status({value}:{value:string}) {
  const positive=['Ativa','Pago','Disponível'].includes(value);
  const negative=['Suspensa','Bloqueado','Vencida','Cancelada'].includes(value);
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${positive?'bg-emerald-50 text-emerald-700':negative?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-800'}`}>{value}</span>;
}

export default function AdminPage() {
  const {user,logout,reloadUser}=useAuth();
  const [section,setSection]=useState('overview');
  const [search,setSearch]=useState('');
  const [query,setQuery]=useState('');
  const [page,setPage]=useState(1);
  const [data,setData]=useState<Data|null>(null);
  const [loading,setLoading]=useState(true);
  const [pending,setPending]=useState(false);
  const [error,setError]=useState('');
  const [notice,setNotice]=useState('');
  const [editor,setEditor]=useState<Editor|null>(null);
  const sequence=useRef(0);
  const fetchData=useCallback(async()=>{
    const request=++sequence.current;setLoading(true);setError('');
    try {const result=await getAdminDataAction(section,query,page);if(request===sequence.current)setData(result);}
    catch(cause){if(request===sequence.current)setError(cause instanceof Error?cause.message:'Não foi possível carregar.');}
    finally{if(request===sequence.current)setLoading(false);}
  },[section,query,page]);
  useEffect(()=>{void fetchData();return()=>{sequence.current++;};},[fetchData]);
  useEffect(()=>{const timeout=setTimeout(()=>{setQuery(search);setPage(1);},300);return()=>clearTimeout(timeout);},[search]);
  useEffect(()=>{if(user?.isPlatformAdmin && user.storeId) void returnToAdminAction().then(()=>reloadUser()).catch(cause=>setError(cause.message));},[user?.uid,user?.storeId,user?.isPlatformAdmin,reloadUser]);
  const navigate=(id:string)=>{setSection(id);setPage(1);setSearch('');setQuery('');setData(null);setNotice('');};
  const open=(kind:string,title:string,values:Record<string,string>={})=>{setError('');setEditor({kind,title,values});};
  const run=async(operation:()=>Promise<unknown>,message='Alteração salva.')=>{
    setPending(true);setError('');setNotice('');
    try {await operation();setEditor(null);setNotice(message);await fetchData();}
    catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível concluir.');}
    finally{setPending(false);}
  };
  const today=data?.today.slice(0,10)??new Date().toISOString().slice(0,10);
  const storeOptions=data?.stores.map(s=>({value:s.id,label:s.name}))??[];
  const planOptions=data?.plans.filter(p=>p.active).map(p=>({value:p.id,label:`${p.name} · ${money(p.priceCents)}/mês`}))??[];
  const fields:Field[]=editor?.kind==='store-create'?[
    {key:'name',label:'Nome da loja',required:true},{key:'cnpj',label:'CNPJ'},{key:'address',label:'Endereço'},{key:'phone',label:'Telefone'},
    {key:'organizationId',label:'Empresa cliente',options:[{value:'',label:'Criar empresa'},...(data?.organizations.map(o=>({value:o.id,label:o.name}))??[])]},{key:'organizationName',label:'Nome da nova empresa (opcional)'},
    {key:'adminName',label:'Nome do administrador da loja',required:true},{key:'adminEmail',label:'E-mail do administrador',type:'email',required:true},{key:'adminPassword',label:'Senha inicial (12 caracteres; vazio para conta existente)',type:'password'},
  ]:editor?.kind==='store-edit'?[
    {key:'name',label:'Nome',required:true},{key:'cnpj',label:'CNPJ'},{key:'address',label:'Endereço'},{key:'phone',label:'Telefone'},
  ]:editor?.kind==='plan'?[
    {key:'name',label:'Nome do plano',required:true},{key:'price',label:'Mensalidade (R$)',type:'number',min:'0',max:'1000000',required:true},{key:'maxUsers',label:'Limite de usuários por loja',type:'number',min:'1',max:'10000',required:true},{key:'active',label:'Disponibilidade',options:[{value:'true',label:'Disponível para contratação'},{value:'false',label:'Retirado do catálogo'}]},{key:'description',label:'Descrição',type:'textarea'},
  ]:editor?.kind==='subscription'?[
    {key:'storeId',label:'Loja',options:storeOptions,required:true,readOnly:!!editor.values.id},{key:'planId',label:'Plano',options:planOptions,required:true},{key:'price',label:'Mensalidade contratada (R$)',type:'number',min:'0',max:'1000000',required:true},{key:'maxUsers',label:'Limite contratado de usuários',type:'number',min:'1',max:'10000',required:true},{key:'nextDue',label:editor.values.id?'Próxima cobrança (controlada pelo sistema)':'Primeiro vencimento',type:'date',readOnly:!!editor.values.id,required:true},{key:'notes',label:'Observações internas',type:'textarea'},
  ]:editor?.kind==='user-create'?[
    {key:'name',label:'Nome',required:true},{key:'email',label:'E-mail',type:'email',required:true},{key:'password',label:'Senha inicial (mínimo 12 caracteres)',type:'password',required:true},{key:'storeId',label:'Loja',options:storeOptions,required:true},{key:'role',label:'Cargo na loja',options:roles,required:true},
  ]:editor?.kind==='grant'?[
    {key:'email',label:'E-mail da conta existente',type:'email',required:true},{key:'storeId',label:'Loja',options:storeOptions,required:true},{key:'role',label:'Cargo na loja',options:roles,required:true},
  ]:editor?.kind==='payment'?[
    {key:'paidAt',label:'Data do recebimento',type:'date',max:today,required:true},{key:'method',label:'Forma de pagamento',options:['Pix','Transferência','Dinheiro','Cartão','Outro'].map(value=>({value,label:value})),required:true},{key:'reference',label:'Referência / comprovante'},{key:'notes',label:'Observações',type:'textarea'},
  ]:editor?.kind==='resume'?[
    {key:'nextDue',label:'Próximo vencimento',type:'date',min:today,required:true},{key:'reason',label:'Motivo',type:'textarea',required:true},
  ]:[...(editor?.kind==='password'?[{key:'password',label:'Nova senha (mínimo 12 caracteres)',type:'password',required:true}]:[]),{key:'reason',label:editor?.kind==='support'?'Motivo do acesso de suporte':'Motivo da alteração',type:'textarea',required:true}];
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{
    event.preventDefault();if(!editor)return;
    const v=editor.values;
    const cents=(value:string)=>{const number=Number(value);if(!Number.isFinite(number)||number<0||Math.abs(number*100-Math.round(number*100))>0.00001)throw new Error('Informe valor em reais com até duas casas decimais.');return Math.round(number*100);};
    await run(async()=>{
      if(editor.kind==='store-create') return createStoreAction({...v,name:v.name,adminName:v.adminName,adminEmail:v.adminEmail,adminPassword:v.adminPassword||'',organizationId:v.organizationId||undefined,organizationName:v.organizationName||undefined});
      if(editor.kind==='store-edit') return saveAdminStoreAction(v);
      if(editor.kind==='plan') return savePlanAction({id:v.id||undefined,name:v.name,priceCents:cents(v.price),maxUsers:Number(v.maxUsers),active:v.active==='true',description:v.description||''});
      if(editor.kind==='subscription') return saveSubscriptionAction({id:v.id||undefined,storeId:v.storeId,planId:v.planId,priceCents:cents(v.price),maxUsers:Number(v.maxUsers),nextDue:v.nextDue,notes:v.notes||''});
      if(editor.kind==='user-create') return createPlatformUserAction(v);
      if(editor.kind==='grant') return grantStoreAccessAction(v.storeId,v.email,v.role);
      if(editor.kind==='payment') return recordInvoicePaymentAction({id:v.id,paidAt:v.paidAt,method:v.method,reference:v.reference||'',notes:v.notes||''});
      if(editor.kind==='store-status') return setAdminStoreStatusAction(v.id,v.status,v.reason);
      if(editor.kind==='subscription-status') return setSubscriptionStatusAction(v.id,v.status,v.reason);
      if(editor.kind==='resume') return resumeSubscriptionAction(v.id,v.nextDue,v.reason);
      if(editor.kind==='invoice-status') return changeInvoiceStatusAction(v.id,v.status,v.reason);
      if(editor.kind==='support') {await selectStoreAction(v.id,v.reason);window.location.assign('/dashboard');return;}
      return manageUserAction({uid:v.uid,operation:editor.kind==='password'?'password':v.operation,reason:v.reason,password:v.password,storeId:v.storeId||undefined});
    });
  };
  const editSubscription=(row:Row)=>open('subscription','Editar assinatura',{id:row.id,storeId:row.storeId,planId:row.planId,price:String(row.priceCents/100),maxUsers:String(row.maxUsers),nextDue:row.nextDue.slice(0,10),notes:row.notes});
  const title=sections.find(s=>s.id===section)!.label;
  const records=(data?.records??[]) as Row[];
  const headers=section==='stores'?['Loja / empresa','Situação','Administrador','Contrato','Ações']:section==='users'?['Conta','Situação','Lojas e cargos','Ações']:section==='plans'?['Plano','Mensalidade','Usuários','Disponibilidade','Ações']:section==='subscriptions'?['Loja / plano','Mensalidade','Situação','Próximo vencimento','Ações']:section==='invoices'?['Loja','Vencimento','Valor','Situação / recebimento','Ações']:['Quando','Ação','Responsável','Detalhes'];
  return <div className="min-h-screen bg-[#f5f7fb] text-slate-900 lg:flex">
    <aside className="border-b border-slate-200 bg-[#101e36] p-5 text-white lg:fixed lg:inset-y-0 lg:w-64 lg:border-b-0">
      <div className="mb-7 flex items-center gap-3"><div className="rounded-xl bg-blue-500 p-2.5"><ShieldCheck size={24}/></div><div><p className="font-semibold tracking-tight">Firma Conecta</p><p className="text-xs text-slate-400">Administração · Alvorada</p></div></div>
      <nav aria-label="Administração da plataforma" className="flex flex-wrap gap-1 lg:block lg:space-y-1">{sections.map(s=><button key={s.id} aria-current={section===s.id?'page':undefined} onClick={()=>navigate(s.id)} className={`flex items-center gap-3 rounded-lg px-3 py-3 text-sm transition lg:w-full ${section===s.id?'bg-blue-500 text-white':'text-slate-300 hover:bg-white/10'}`}><s.icon size={18}/>{s.label}</button>)}</nav>
      <div className="mt-6 rounded-xl border border-white/10 p-4 lg:absolute lg:bottom-5 lg:left-5 lg:right-5"><p className="text-xs uppercase tracking-wider text-blue-300">Conta global</p><p className="mt-2 break-all text-sm">{user?.email??'Carregando…'}</p><button onClick={()=>void run(async()=>{await logout();window.location.assign('/');})} className="mt-4 flex items-center gap-2 text-sm text-slate-300 hover:text-white" disabled={pending}><LogOut size={16}/>Sair</button></div>
    </aside>
    <div className="min-w-0 flex-1 lg:ml-64">
      <header className="flex items-center justify-between border-b border-slate-200 bg-white px-5 py-4 lg:px-9"><div><p className="text-xs font-medium uppercase tracking-widest text-slate-400">Central da plataforma</p><p className="mt-1 text-sm text-slate-600">Gestão comercial e de acessos</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={16} className="text-blue-600"/>Administrador global<UserNav /></div></header>
      <main className="mx-auto max-w-[1500px] space-y-6 p-5 lg:p-9">
        <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-1 text-sm text-slate-500">{section==='overview'?'Acompanhe sua carteira de lojas, contratos e recebimentos.':section==='invoices'?'Cobranças mensais por loja. Confirmação de recebimento manual.':section==='subscriptions'?'Um contrato independente por loja, com preço e limite próprios.':section==='audit'?'Histórico de alterações e acessos administrativos.':'Organize e gerencie os dados da plataforma.'}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void fetchData()} disabled={loading||pending}><RefreshCw size={16} className={loading?'mr-2 animate-spin':'mr-2'}/>Atualizar</Button>{section==='stores'&&<Button onClick={()=>open('store-create','Criar loja',{organizationId:'',cnpj:'',address:'',phone:''})}><Plus size={16} className="mr-2"/>Criar loja</Button>}{section==='users'&&<><Button variant="outline" onClick={()=>open('grant','Vincular conta existente',{storeId:storeOptions[0]?.value??'',role:'Administrador'})}>Vincular usuário</Button><Button onClick={()=>open('user-create','Criar usuário',{storeId:storeOptions[0]?.value??'',role:'Operador de Caixa'})}><Plus size={16} className="mr-2"/>Criar usuário</Button></>}{section==='plans'&&<Button onClick={()=>open('plan','Criar plano',{price:'',maxUsers:'5',active:'true',description:''})}><Plus size={16} className="mr-2"/>Criar plano</Button>}{section==='subscriptions'&&<Button disabled={!planOptions.length} onClick={()=>open('subscription','Criar assinatura',{storeId:storeOptions[0]?.value??'',planId:planOptions[0]?.value??'',price:String((data?.plans.find(p=>p.id===planOptions[0]?.value)?.priceCents??0)/100),maxUsers:String(data?.plans.find(p=>p.id===planOptions[0]?.value)?.maxUsers??5),nextDue:today,notes:''})}><Plus size={16} className="mr-2"/>Criar assinatura</Button>}{section==='invoices'&&<Button onClick={()=>void run(()=>syncBillingAction(),'Cobranças sincronizadas.')} disabled={pending}><RefreshCw size={16} className="mr-2"/>Gerar cobranças devidas</Button>}</div></div>
        {error&&!editor&&<div role="alert" className="flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><AlertCircle size={18}/>{error}</div>}
        {notice&&<div role="status" className="flex gap-2 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 size={18}/>{notice}</div>}
        {section==='overview'&&data&&<>
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{label:'Lojas ativas',value:String(data.metrics.activeStores),detail:`${data.metrics.storeCount} lojas cadastradas`,icon:Building2},{label:'Receita recorrente mensal',value:money(data.metrics.recurring),detail:`${data.metrics.activeSubscriptions} assinaturas ativas`,icon:CreditCard},{label:'Recebido neste mês',value:money(data.metrics.received),detail:'Pagamentos confirmados manualmente',icon:Receipt},{label:'Cobranças em aberto',value:money(data.metrics.pending),detail:`${data.metrics.overdue} cobranças vencidas`,icon:AlertCircle}].map(m=><div key={m.label} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{m.label}</p><m.icon size={19} className="text-blue-500"/></div><p className="mt-4 text-3xl font-semibold tracking-tight">{m.value}</p><p className="mt-2 text-xs text-slate-500">{m.detail}</p></div>)}</div>
          <div className="grid gap-5 xl:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-6 xl:col-span-2"><h2 className="font-semibold">Pendências e próximos passos</h2><div className="mt-4 divide-y">{[{label:'Lojas sem assinatura',value:data.metrics.storeCount-data.metrics.activeSubscriptions,description:'Confira contratos pausados, cancelados e lojas ainda sem plano.',target:'subscriptions'},{label:'Cobranças vencidas',value:data.metrics.overdue,description:'Revise o recebimento e registre os pagamentos.',target:'invoices'},{label:'Contas operacionais habilitadas',value:data.metrics.userCount,description:'Gerencie vínculos e permissões por loja.',target:'users'}].map(item=><button key={item.label} onClick={()=>navigate(item.target)} className="flex w-full items-center justify-between gap-4 py-4 text-left"><div><p className="text-sm font-medium">{item.label} <span className="ml-2 rounded bg-slate-100 px-2 py-1 text-xs">{item.value}</span></p><p className="mt-1 text-xs text-slate-500">{item.description}</p></div><ArrowUpRight size={18} className="text-blue-500"/></button>)}</div></div><div className="rounded-2xl bg-[#101e36] p-6 text-white"><Layers className="text-blue-300"/><h2 className="mt-4 text-lg font-semibold">Assinaturas por loja</h2><p className="mt-3 text-sm leading-6 text-slate-300">Configure seus planos e vincule cada loja ao seu contrato. Os vencimentos são gerados automaticamente; você confirma os pagamentos.</p><p className="mt-4 text-xs leading-5 text-slate-400">Atrasos geram alertas. A suspensão da loja permanece uma decisão manual.</p><Button className="mt-5 bg-blue-500 hover:bg-blue-600" onClick={()=>navigate('plans')}>Configurar planos</Button></div></div>
        </>}
        {section!=='overview'&&<div className="relative max-w-md"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><Input aria-label="Buscar registros" placeholder={section==='audit'?'Buscar ação, responsável ou detalhes…':'Buscar por nome…'} value={search} onChange={e=>setSearch(e.target.value)} className="border-slate-200 bg-white pl-10"/></div>}
        <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
          {section==='overview'&&<div className="flex items-center justify-between border-b p-5"><h2 className="font-semibold">Atividades recentes</h2><button onClick={()=>navigate('audit')} className="text-sm text-blue-600">Ver histórico</button></div>}
          {loading?<div role="status" className="p-10 text-center text-sm text-slate-500">Carregando dados…</div>:records.length===0?<div className="p-12 text-center"><Layers className="mx-auto text-slate-300" size={32}/><p className="mt-3 font-medium">Nenhum registro encontrado</p><p className="mt-2 text-sm text-slate-500">{section==='plans'?'Crie o primeiro plano com os valores da sua operação.':section==='subscriptions'?'Cadastre um plano e crie o contrato de cada loja.':'Os registros aparecerão aqui conforme você usar o painel.'}</p></div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{headers.map(h=><th key={h} scope="col" className="whitespace-nowrap px-5 py-4 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{records.map(row=><tr key={row.id||row.uid} className="align-top hover:bg-slate-50/50">
            {section==='stores'?<><td className="px-5 py-4"><p className="font-medium">{row.name}</p><p className="mt-1 text-xs text-slate-500">{row.organization.name}</p><p className="mt-1 text-xs text-slate-400">{row.cnpj||'CNPJ não informado'}</p></td><td className="px-5 py-4"><Status value={row.status}/><p className="mt-2 text-xs text-slate-500">{row._count.memberships} usuários</p></td><td className="px-5 py-4 text-xs">{row.memberships?.map(m=>m.user.email).join(', ')||'Sem administrador'}</td><td className="px-5 py-4 text-xs">{row.subscription?.plan.name||'Sem assinatura'}</td><td className="px-5 py-4"><div className="flex max-w-xs flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>open('store-edit','Editar loja',{id:row.id,name:row.name,cnpj:row.cnpj??'',address:row.address??'',phone:row.phone??''})}>Editar</Button><Button size="sm" variant="outline" onClick={()=>open('grant','Vincular usuário',{storeId:row.id,role:'Administrador'})}>Acessos</Button><Button size="sm" variant="outline" disabled={row.status!=='Ativa'} onClick={()=>open('support',`Acesso de suporte · ${row.name}`,{id:row.id})}>Suporte</Button><Button size="sm" variant="outline" onClick={()=>open('store-status',row.status==='Ativa'?'Suspender loja':'Reativar loja',{id:row.id,status:row.status==='Ativa'?'Suspensa':'Ativa'})}>{row.status==='Ativa'?'Suspender':'Reativar'}</Button></div></td></>:
            section==='users'?<><td className="px-5 py-4"><p className="font-medium">{row.name}</p><p className="mt-1 text-xs text-slate-500">{row.email}</p></td><td className="px-5 py-4"><Status value={row.isPlatformAdmin?'Global':row.disabled?'Bloqueado':'Ativa'}/></td><td className="space-y-2 px-5 py-4">{row.memberships?.map(m=><div key={m.store.id} className="text-xs"><p>{m.store.name} · {m.role}</p>{!row.isPlatformAdmin&&<div className="mt-1 flex gap-2"><button className="text-blue-600" onClick={()=>open('grant','Alterar cargo',{email:row.email,storeId:m.store.id,role:m.role})}>Alterar cargo</button><button className="text-rose-600" onClick={()=>open('user','Remover vínculo',{uid:row.uid,operation:'unlink',storeId:m.store.id})}>Remover vínculo</button></div>}</div>)||'Sem vínculos'}{row.isPlatformAdmin&&<p className="text-xs text-slate-500">Administração exclusiva da plataforma</p>}</td><td className="px-5 py-4">{!row.isPlatformAdmin&&<div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>open('user',row.disabled?'Reativar conta':'Bloquear conta',{uid:row.uid,operation:row.disabled?'unblock':'block'})}>{row.disabled?'Reativar':'Bloquear'}</Button><Button size="sm" variant="outline" onClick={()=>open('password','Redefinir senha',{uid:row.uid})}>Senha</Button><Button size="sm" variant="outline" onClick={()=>open('user','Revogar sessões',{uid:row.uid,operation:'revoke'})}>Revogar sessões</Button></div>}</td></>:
            section==='plans'?<><td className="px-5 py-4"><p className="font-medium">{row.name}</p><p className="mt-1 max-w-xs text-xs text-slate-500">{row.description}</p></td><td className="px-5 py-4">{money(row.priceCents)} / mês</td><td className="px-5 py-4">{row.maxUsers}</td><td className="px-5 py-4"><Status value={row.active?'Disponível':'Retirado'}/><p className="mt-2 text-xs text-slate-500">{row._count.subscriptions} contratos</p></td><td className="px-5 py-4"><Button variant="outline" size="sm" onClick={()=>open('plan','Editar plano',{id:row.id,name:row.name,price:String(row.priceCents/100),maxUsers:String(row.maxUsers),active:String(row.active),description:row.description})}>Editar</Button></td></>:
            section==='subscriptions'?<><td className="px-5 py-4"><p className="font-medium">{row.store.name}</p><p className="mt-1 text-xs text-slate-500">{row.plan.name} · até {row.maxUsers} usuários</p></td><td className="px-5 py-4">{money(row.priceCents)}</td><td className="px-5 py-4"><Status value={row.status}/></td><td className="px-5 py-4">{row.status==='Ativa'?date(row.nextDue):'Geração interrompida'}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>editSubscription(row)}>Editar contrato</Button>{row.status==='Ativa'?<Button size="sm" variant="outline" onClick={()=>open('subscription-status','Pausar assinatura',{id:row.id,status:'Pausada'})}>Pausar</Button>:<Button size="sm" variant="outline" onClick={()=>open('resume','Retomar assinatura',{id:row.id,nextDue:today})}>Retomar</Button>}{row.status!=='Cancelada'&&<Button size="sm" variant="outline" onClick={()=>open('subscription-status','Cancelar assinatura',{id:row.id,status:'Cancelada'})}>Cancelar</Button>}</div></td></>:
            section==='invoices'?<><td className="px-5 py-4 font-medium">{row.subscription?.store.name}</td><td className="px-5 py-4">{date(row.dueDate)}</td><td className="px-5 py-4">{money(row.amountCents)}</td><td className="px-5 py-4"><Status value={row.status==='Pendente'&&row.dueDate<data!.today?'Vencida':row.status}/>{row.paidAt&&<p className="mt-2 text-xs text-slate-500">{date(row.paidAt)} · {row.paymentMethod}<br/>{row.paymentReference}</p>}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-2">{row.status==='Pendente'&&<><Button size="sm" onClick={()=>open('payment',`Registrar recebimento · ${money(row.amountCents)}`,{id:row.id,paidAt:today,method:'Pix'})}>Registrar pagamento</Button><Button size="sm" variant="outline" onClick={()=>open('invoice-status','Cancelar cobrança',{id:row.id,status:'Cancelada'})}>Cancelar</Button></>}{row.status!=='Pendente'&&<Button size="sm" variant="outline" onClick={()=>open('invoice-status',row.status==='Pago'?'Estornar registro de pagamento':'Reabrir cobrança',{id:row.id,status:'Pendente'})}>{row.status==='Pago'?'Estornar registro':'Reabrir'}</Button>}</div></td></>:
            <><td className="whitespace-nowrap px-5 py-4 text-xs text-slate-500">{new Date(row.date).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</td><td className="px-5 py-4 font-medium">{row.action}</td><td className="px-5 py-4">{row.actorName}</td><td className="max-w-xl px-5 py-4 text-xs leading-5 text-slate-500">{row.details}</td></>}
          </tr>)}</tbody></table></div>}
          {section!=='overview'&&data&&<div className="flex items-center justify-between border-t px-5 py-4 text-xs text-slate-500"><p>{data.total} registros · página {page} de {Math.max(1,Math.ceil(data.total/20))}</p><div className="flex gap-2"><Button size="sm" variant="outline" aria-label="Página anterior" disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></Button><Button size="sm" variant="outline" aria-label="Próxima página" disabled={page*20>=data.total||loading} onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></Button></div></div>}
        </div>
        <p className="text-xs text-slate-400">Firma Conecta · Mensalidades e recebimentos da plataforma. Dados comerciais das lojas permanecem separados.</p>
      </main>
    </div>
    <Dialog open={!!editor} onOpenChange={value=>{if(!value&&!pending){setEditor(null);setError('');}}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{editor?.title}</DialogTitle><DialogDescription>{editor?.kind==='store-create'?'A nova loja começa com seus próprios dados, sem produtos, clientes ou vendas.':editor?.kind==='plan'?'Alterar o catálogo não modifica preços e limites de contratos existentes.':editor?.kind==='subscription'?'Contrato mensal independente para esta loja. Valores são confirmados manualmente.':editor?.kind==='support'?'Você acessará a operação com sua identidade global. O acesso será registrado.':editor?.kind==='payment'?'Confirme somente pagamentos efetivamente recebidos. Esta ação não processa uma transação bancária.':'A alteração ficará registrada na auditoria. Bloqueios e redefinições revogam as sessões da conta.'}</DialogDescription></DialogHeader>
      <form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">{fields.map(field=><div key={field.key} className={field.type==='textarea'?'sm:col-span-2':''}><Label htmlFor={`admin-${field.key}`}>{field.label}</Label>{field.options?<select id={`admin-${field.key}`} required={field.required} disabled={field.readOnly||pending} className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={editor?.values[field.key]??field.options[0]?.value??''} onChange={e=>{const value=e.target.value;setEditor(current=>{if(!current)return current;const values={...current.values,[field.key]:value};if(field.key==='planId'){const plan=data?.plans.find(p=>p.id===value);if(plan){values.price=String(plan.priceCents/100);values.maxUsers=String(plan.maxUsers);}}return {...current,values};});}}>{field.options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:field.type==='textarea'?<textarea id={`admin-${field.key}`} required={field.required} maxLength={2000} disabled={pending} className="mt-1 min-h-24 w-full rounded-md border bg-background p-3 text-sm" value={editor?.values[field.key]??''} onChange={e=>setEditor(current=>current?{...current,values:{...current.values,[field.key]:e.target.value}}:null)}/>:<Input id={`admin-${field.key}`} type={field.type??'text'} required={field.required} disabled={pending} readOnly={field.readOnly} min={field.min} max={field.max} step={field.type==='number'?(field.key==='maxUsers'?'1':'0.01'):undefined} minLength={field.type==='password'?12:undefined} autoComplete={field.type==='password'?'new-password':'off'} value={editor?.values[field.key]??''} onChange={e=>setEditor(current=>current?{...current,values:{...current.values,[field.key]:e.target.value}}:null)} className="mt-1"/>}</div>)}</div>
        {error&&<p role="alert" className="rounded-md bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" disabled={pending} onClick={()=>{setEditor(null);setError('');}}>Cancelar</Button><Button type="submit" disabled={pending}>{pending?'Salvando…':editor?.kind==='support'?'Acessar loja':'Confirmar'}</Button></div>
      </form>
    </DialogContent></Dialog>
  </div>;
}
