import assert from 'node:assert/strict';
import {stockAdjustmentSchema,receiveStockItemSchema,stockQuantityInput} from '../src/lib/stock-input';
import {validateOfflineOperation} from '../src/lib/offline-validation';
import {projectOperations} from '../src/lib/offline-projection';
import type {User} from '../src/lib/types';
let checks=0;
function check(name:string,run:()=>void){run();checks++;console.log('PASS '+name);}
const user:User={uid:'fixture-user',name:'Fixture',email:'fixture@example.invalid',role:'Estoquista',storeId:'fixture-store'};
const data={products:[{id:'p',name:'Produto',status:'Ativo',stock:10,averageCost:0,costHistory:[]}],suppliers:[{id:'s'}],purchaseOrders:[{id:'order',status:'Pendente',items:[{productId:'p',quantityOrdered:4.5,quantityReceived:1}]}]};
check('raw adjustment string becomes a number',()=>{const parsed=stockAdjustmentSchema.parse({newQuantity:'15',reason:'Contagem'});assert.equal(parsed.newQuantity,15);validateOfflineOperation('adjustStock',['p',parsed.newQuantity,parsed.reason,''],data,user);});
check('fractional adjustment',()=>assert.equal(stockAdjustmentSchema.parse({newQuantity:'2.75',reason:'Contagem'}).newQuantity,2.75));
check('zero adjustment',()=>assert.equal(stockAdjustmentSchema.parse({newQuantity:'0',reason:'Perda'}).newQuantity,0));
check('negative adjustment rejected',()=>assert.equal(stockAdjustmentSchema.safeParse({newQuantity:-1,reason:'Contagem'}).success,false));
check('invalid adjustment rejected',()=>assert.equal(stockAdjustmentSchema.safeParse({newQuantity:'abc',reason:'Contagem'}).success,false));
check('missing reason rejected',()=>assert.equal(stockAdjustmentSchema.safeParse({newQuantity:10}).success,false));
check('entry retains decimals',()=>assert.equal(stockQuantityInput('0.75'),0.75));
check('blank entry rejected by offline validation',()=>assert.throws(()=>validateOfflineOperation('addStock',[[{productId:'p',quantity:stockQuantityInput(''),cost:1}],{id:'s'}],data,user)));
const receipt={productId:'p',productName:'Produto',quantityOrdered:4.5,quantityAlreadyReceived:1,quantityReceived:'0.75',cost:'2.50'};
check('fractional receipt is parsed',()=>assert.equal(receiveStockItemSchema.parse(receipt).quantityReceived,.75));
check('excess receipt rejected',()=>assert.equal(receiveStockItemSchema.safeParse({...receipt,quantityReceived:4}).success,false));
check('entry valid for stock clerk',()=>validateOfflineOperation('addStock',[[{productId:'p',quantity:.75,cost:2.5}],{id:'s'}],data,user));
check('duplicate entry rejected',()=>assert.throws(()=>validateOfflineOperation('addStock',[[{productId:'p',quantity:1,cost:1},{productId:'p',quantity:1,cost:1}],{id:'s'}],data,user)));
check('unknown supplier rejected',()=>assert.throws(()=>validateOfflineOperation('addStock',[[{productId:'p',quantity:1,cost:1}],{id:'missing'}],data,user)));
check('receipt valid for stock clerk',()=>validateOfflineOperation('receivePurchaseOrder',['order',[receiveStockItemSchema.parse(receipt)]],data,user));
check('excess receipt rejected locally',()=>assert.throws(()=>validateOfflineOperation('receivePurchaseOrder',['order',[{productId:'p',quantityReceived:5,cost:1}]],data,user)));
check('stock changes denied for cashier',()=>{for(const kind of ['adjustStock','addStock','receivePurchaseOrder'])assert.throws(()=>validateOfflineOperation(kind,[],data,{...user,role:'Operador de Caixa'}));});
check('offline adjustment projects exact value',()=>{const op:any={id:'op',kind:'adjustStock',args:['p',2.75,'Contagem',''],createdAt:new Date().toISOString()};const projected=projectOperations(data,[op],user);assert.equal(projected.products[0].stock,2.75);assert.equal(projected.stockAdjustmentLogs[0].oldQuantity,10);});
check('offline receipt projects stock and pending balance',()=>{const op:any={id:'op',kind:'receivePurchaseOrder',args:['order',[{productId:'p',quantityReceived:.75,cost:2.5}]],createdAt:new Date().toISOString()};const projected=projectOperations(data,[op],user);assert.equal(projected.products[0].stock,10.75);assert.equal(projected.purchaseOrders[0].items[0].quantityReceived,1.75);assert.equal(projected.purchaseOrders[0].status,'Recebido Parcialmente');});
console.log(`${checks} stock checks passed; no database writes.`);
