import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {restrictDataPlan} from '../src/lib/data-access';
import {dataPlan} from '../src/lib/data-plan';
import {recordLoginAttempt,clearLoginAttempts} from '../src/lib/login-rate-limit';
const plan=(role:any,page:string)=>restrictDataPlan(role,dataPlan(page));
assert.throws(()=>plan('Estoquista','/dashboard/customers'));
assert.throws(()=>plan('Estoquista','/dashboard/sales'));
assert.throws(()=>plan('Operador de Caixa','/dashboard/accounts-payable'));
assert.equal(plan('Estoquista','/offline').needed.has('customers'),false);
assert.equal(plan('Estoquista','/offline').needed.has('sales'),false);
assert.equal(plan('Estoquista','/offline').needed.has('cashSessions'),false);
assert.equal(plan('Estoquista','/offline').needed.has('purchaseOrders'),true);
assert.equal(plan('Operador de Caixa','/pos').needed.has('customers'),true);
assert.equal(plan('Operador de Caixa','/offline').needed.has('allUsers'),false);
assert.equal(plan('Administrador','/offline').needed.has('allUsers'),true);
assert.equal(plan('Gerente','/offline').needed.has('allUsers'),false);
process.env.ALVORADA_SECURITY_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'granzoti-rate-check-'));
process.env.AUTH_SESSION_SECRET='fixture-only-not-a-production-secret';
recordLoginAttempt('fixture',1);
assert.throws(()=>recordLoginAttempt('fixture',1));
const child="import {recordLoginAttempt} from './src/lib/login-rate-limit'; try{recordLoginAttempt('fixture',1);process.exit(1)}catch{process.exit(0)}";
execFileSync(process.execPath,['node_modules/tsx/dist/cli.mjs','-e',child],{env:process.env});
clearLoginAttempts('fixture');recordLoginAttempt('fixture',1);
console.log('15 security checks passed. Fixtures only; no production database writes.');
