import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PrismaClient} from '@prisma/client';
import bcrypt from 'bcryptjs';
async function main(){
 const runtime=new URL(process.env.DATABASE_URL!),ownerUrl=new URL(process.env.DIRECT_DATABASE_URL!);assert.equal(runtime.searchParams.get('schema'),'alvorada_improvements_20261009_test');assert.equal(ownerUrl.searchParams.get('schema'),runtime.searchParams.get('schema'));
 const owner=new PrismaClient({datasourceUrl:ownerUrl.toString()});const {withDbContext,prisma}=await import('../src/lib/db');const a=await import('../src/lib/db-actions'),reports=await import('../src/lib/operational-actions'),units=await import('../src/lib/measure-unit-actions'),admin=await import('../src/lib/admin-actions'),proofs=await import('../src/lib/invoice-proof-actions');const {processSale}=await import('../src/lib/sales-service');let checks=0;const check=(name:string)=>{checks++;console.log('PASS '+name)};
 try{
 const organization=await owner.organization.create({data:{name:'Improvements test'}}),store=await owner.store.create({data:{name:'Improvements store',organizationId:organization.id}}),other=await owner.store.create({data:{name:'Other test store',organizationId:organization.id}});
 const user:any={uid:randomUUID(),name:'Test admin',email:randomUUID()+'@test.invalid',role:'Administrador',storeId:store.id,store:{...store,cnpj:'',address:'',phone:''}},global:any={uid:randomUUID(),name:'Test global',email:randomUUID()+'@test.invalid',role:'Administrador',isPlatformAdmin:true};
 const hash=await bcrypt.hash('DisposableImprovements123!',12);await owner.user.create({data:{uid:user.uid,name:user.name,email:user.email,role:user.role,storeId:store.id,passwordHash:hash,memberships:{create:{storeId:store.id,role:user.role}}}});await owner.user.create({data:{uid:global.uid,name:global.name,email:global.email,role:global.role,isPlatformAdmin:true,passwordHash:hash}});
 const local=<T>(fn:()=>Promise<T>)=>withDbContext({uid:user.uid,storeId:store.id,user},fn),platform=<T>(fn:()=>Promise<T>)=>withDbContext({uid:global.uid,platformAdmin:true,user:global},fn);
 await local(()=>a.addProductAction({name:'Coca test 2 L',category:'Bebidas',price:10,stock:20,minStock:2,unit:'2 L',measurement:{factor:2,baseUnit:'L'}},store.id));const product=await owner.product.findFirstOrThrow({where:{storeId:store.id}});assert.equal(product.supplier,'');check('product accepts absent supplier and valid conversion');
 await local(()=>units.createMeasureUnitAction(store.id,'Fardo 12 garrafas',{factor:24,baseUnit:'L'}));assert.ok((await local(()=>units.getMeasureUnitsAction(store.id))).some(u=>u.label==='Fardo 12 garrafas'));await assert.rejects(local(()=>units.createMeasureUnitAction(store.id,'Fardo 12 garrafas')));await assert.rejects(local(()=>units.createMeasureUnitAction(store.id,'Inválida',{factor:-1,baseUnit:'L'})));check('unit catalog persists and rejects duplicates and invalid factors');
 const session=await owner.cashRegisterSession.create({data:{storeId:store.id,openingBalance:100,calculatedCashInDrawer:100,totalSales:0,totalExpenses:0,totalWithdrawals:0,totalCreditPayments:0,salesByPaymentMethod:{Dinheiro:0,Cartão:0,Pix:0},status:'Aberto',openedByUid:user.uid,openedByName:user.name}});
 const request:any={clientRequestId:randomUUID(),items:[{productId:product.id,productName:'Client label',quantity:3,price:10,measurement:{factor:999,baseUnit:'L'}}],total:30,customerId:'default',customerName:'Client label',paymentMethods:[{method:'Dinheiro',amount:30}]};
 const sale=await local(()=>processSale(request,session.id,user));const replay=await local(()=>processSale(request,session.id,user));assert.equal(replay.id,sale.id);assert.equal((await owner.product.findUniqueOrThrow({where:{id:product.id}})).stock,17);assert.equal((sale.items as any)[0].measurement.factor,2);assert.equal((await owner.cashRegisterSession.findUniqueOrThrow({where:{id:session.id}})).totalSales,30);check('lost-response replay has one sale, one stock decrement and authoritative conversion');
 await owner.sale.update({where:{id:sale.id},data:{date:new Date('2026-01-01T02:59:59Z')}});await owner.sale.create({data:{...sale,id:randomUUID(),clientRequestId:randomUUID(),date:new Date('2026-01-01T03:00:00Z')} as any});
 const report=await local(()=>reports.getBusinessReportAction(store.id,'2025-12-31','2026-01-01'));assert.deepEqual(report.days.map(d=>d.day),['2025-12-31','2026-01-01']);assert.equal(report.current.revenue,60);assert.equal(report.products[0].liters,12);const exported=await local(()=>reports.exportSalesAction(store.id,'2025-12-31','2026-01-01'));assert.equal(exported.rows.reduce((n,s)=>n+s.total,0),report.current.revenue);check('timezone/year boundaries, snapshots and CSV totals reconcile');
 await owner.product.update({where:{id:product.id},data:{measurement:{factor:1,baseUnit:'L'}}});const preserved=await local(()=>reports.getBusinessReportAction(store.id,'2025-12-31','2026-01-01'));assert.equal(preserved.products[0].liters,12);check('editing product conversion does not rewrite historical liters');
 await owner.product.create({data:{name:'Secret other store',sku:'OTHER',storeId:other.id,status:'Ativo',category:'Bebidas',price:1,stock:1,minStock:0,averageCost:0,costHistory:[],unit:'un',supplier:''}});
 assert.equal((await local(()=>reports.searchStoreAction('Secret',store.id))).length,0);await assert.rejects(local(()=>reports.searchStoreAction('Secret',other.id)));check('search and report store ownership enforced');
 const additions=Array.from({length:120},(_,i)=>({name:'Pagination '+i,sku:'P'+i,storeId:store.id,status:'Ativo',category:'Outros',price:1,averageCost:0,costHistory:[],stock:1,minStock:0,unit:'un',supplier:''}));await owner.product.createMany({data:additions});
 const page1=await local(()=>a.getInitialDataAction(store.id,'/dashboard/products',1)),page2=await local(()=>a.getInitialDataAction(store.id,'/dashboard/products',2)),customers=await local(()=>a.getInitialDataAction(store.id,'/dashboard/customers'));
 assert.equal(page1.products.length,50);assert.equal(page1.meta.total,121);assert.ok(!page1.products.some(p=>page2.products.some(q=>q.id===p.id)));assert.equal(customers.sales.length,0);console.log('MEASURED products_page_bytes='+Buffer.byteLength(JSON.stringify(page1))+' customers_page_bytes='+Buffer.byteLength(JSON.stringify(customers)));check('bounded server pagination and customer loading exclude all sales');
 const supplier=await owner.supplier.create({data:{name:'Supplier fixture',storeId:store.id}});const order=await owner.purchaseOrder.create({data:{storeId:store.id,supplierId:supplier.id,supplierName:supplier.name,status:'Pendente',dateExpected:new Date(),items:[{productId:product.id,productName:product.name,quantityOrdered:10,quantityReceived:0,cost:3}],totalCost:30,registeredByUid:user.uid,registeredByName:user.name}});
 const item={productId:product.id,productName:product.name,quantityReceived:4,cost:3};await local(()=>a.receivePurchaseOrderAction(order.id,[item],store.id));assert.equal((await owner.purchaseOrder.findUniqueOrThrow({where:{id:order.id}})).status,'Recebido Parcialmente');await assert.rejects(local(()=>a.receivePurchaseOrderAction(order.id,[{...item,quantityReceived:7}],store.id)));await assert.rejects(local(()=>a.receivePurchaseOrderAction(order.id,[item,item],store.id)));await local(()=>a.receivePurchaseOrderAction(order.id,[{...item,quantityReceived:6}],store.id));await assert.rejects(local(()=>a.receivePurchaseOrderAction(order.id,[item],store.id)));check('partial receipts retain remaining quantity; overreceipt and replay rejected');
 const customer=await owner.customer.create({data:{name:'Ledger fixture',storeId:store.id,phone:'',tags:[],creditLimit:100,balance:0,loyaltyPoints:0}});await local(()=>processSale({...request,clientRequestId:randomUUID(),items:[{productId:product.id,productName:product.name,quantity:1,price:10}],total:10,customerId:customer.id,paymentMethods:[{method:'Fiado',amount:10}]},session.id,user));await local(()=>a.addCreditPaymentAction(customer.id,4,session.id,store.id));const ledger=await local(()=>reports.getCustomerLedgerAction(store.id,customer.id));assert.equal(ledger.customer.balance,6);assert.equal(ledger.rows[0].balance,6);assert.equal(ledger.openingBalance,0);check('unified customer ledger reconciles credit and loyalty balances');
 await local(()=>a.closeCashRegisterAction(session.id,130,store.id,{Cartão:0,Pix:0}));await assert.rejects(local(()=>a.closeCashRegisterAction(session.id,130,store.id)));await assert.rejects(local(()=>a.correctCashClosingAction(session.id,132,store.id,'')));await local(()=>a.correctCashClosingAction(session.id,132,store.id,'Conferência de teste'));await local(()=>a.correctCashClosingAction(session.id,134,store.id,'Segunda conferência'));const closing=await owner.cashRegisterSession.findUniqueOrThrow({where:{id:session.id}});assert.equal((closing.correction as any).history.length,1);assert.equal((closing.closingByPaymentMethod as any).Dinheiro,134);assert.equal(await owner.auditLog.count({where:{storeId:store.id,action:'Correção de Saldo de Fechamento'}}),2);check('close guard and correction reasons preserve every before/after');
 await local(()=>processSale(request,session.id,user));assert.equal(await owner.sale.count({where:{clientRequestId:request.clientRequestId}}),1);check('same request is recognized after register closure');
 const limited:any={...user,role:'Operador de Caixa'};await assert.rejects(withDbContext({uid:user.uid,storeId:store.id,user:limited},()=>reports.getBusinessReportAction(store.id,'2025-12-31','2026-01-01')));check('direct report calls respect role checks');
 await platform(()=>admin.manageUserAction({uid:user.uid,operation:'password',password:'TemporaryPassword123!',reason:'Teste temporário'}));assert.equal((await owner.user.findUniqueOrThrow({where:{uid:user.uid}})).mustChangePassword,true);const temporary={...user,mustChangePassword:true};await assert.rejects(withDbContext({uid:user.uid,storeId:store.id,user:temporary},()=>a.getInitialDataAction(store.id)));check('administrative reset revokes sessions and blocks operations until own password change');
 const plan=await owner.plan.create({data:{name:'Fixture plan',priceCents:9000,maxUsers:5}}),contract=await owner.subscription.create({data:{storeId:store.id,planId:plan.id,priceCents:8000,maxUsers:5,status:'Ativa',nextDue:new Date('2026-11-01T12:00Z'),billingDay:1}});await owner.invoice.create({data:{subscriptionId:contract.id,dueDate:new Date('2026-09-01T12:00Z'),amountCents:8000,status:'Pendente'}});await platform(()=>admin.savePlanAction({id:plan.id,name:plan.name,priceCents:10000,maxUsers:5,active:true,description:''}));assert.equal((await owner.subscription.findUniqueOrThrow({where:{id:contract.id}})).priceCents,8000);const billing=await platform(()=>admin.getAdminDataAction('invoices','',1,{status:'Vencida',storeId:store.id}));assert.equal(billing.total,1);assert.ok(billing.aging.some(a=>a.amount>=8000));check('manual invoice filters and aging preserve contracted prices');
 const invoice=await owner.invoice.findFirstOrThrow({where:{subscriptionId:contract.id}});const form=new FormData();form.set('invoiceId',invoice.id);form.set('file',new File(['%PDF-1.4\nDisposable fixture'],'comprovante.pdf',{type:'application/pdf'}));const proof=await platform(()=>proofs.uploadInvoiceProofAction(form));assert.ok(proof.id);assert.equal((await local(()=>prisma.invoiceAttachment.findMany())).length,0);const invalid=new FormData();invalid.set('invoiceId',invoice.id);invalid.set('file',new File(['malicious'],'invalid.pdf',{type:'application/pdf'}));await assert.rejects(platform(()=>proofs.uploadInvoiceProofAction(invalid)));check('private proof upload validates signatures and denies shop access');
 console.log('IMPROVEMENTS_TESTS_PASSED '+checks);
 }finally{await owner.$disconnect();await prisma.$disconnect();}
}
main().catch(e=>{console.error(e);process.exitCode=1});
