'use client';
import {useCallback,useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {getMaintenanceAdminAction,saveMaintenanceAction,savePlatformMessageAction,archivePlatformMessageAction} from '@/lib/maintenance-actions';
import {refreshPlatformStatus} from '@/lib/platform-status-client';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Message={id:string;kind:'notice'|'patchnotes';title:string;body:string;version:string;publishedAt:string|null;archived:boolean};
type Data={maintenance:{enabled:boolean;message:string;expectedReturn:string|null;revision:number};messages:Message[]};
const empty={kind:'notice' as 'notice'|'patchnotes',title:'',body:'',version:'',id:undefined as string|undefined};
export function MaintenanceAdmin(){
 const [data,setData]=useState<Data|null>(null),[pending,setPending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [message,setMessage]=useState(''),[returnAt,setReturnAt]=useState(''),[reason,setReason]=useState(''),[confirm,setConfirm]=useState<boolean|null>(null);
 const [draft,setDraft]=useState(empty),[publish,setPublish]=useState(false);
 const load=useCallback(async()=>{const next:Data=await getMaintenanceAdminAction();setData(next);setMessage(next.maintenance.message);setReturnAt(next.maintenance.expectedReturn?new Date(next.maintenance.expectedReturn).toLocaleString('sv-SE',{timeZone:'America/Sao_Paulo'}).replace(' ','T').slice(0,16):'');},[]);
 useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
 const run=async(action:()=>Promise<unknown>,text:string)=>{setPending(true);setError('');setNotice('');try{await action();await load();setNotice(text);void refreshPlatformStatus().catch(()=>{});return true;}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');return false;}finally{setPending(false);}};
 return <div className="space-y-6">
  {error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-4 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded bg-green-50 p-4 text-green-800">{notice}</p>}
  {!data?<p>Carregando manutenção…</p>:<>
   <section className="space-y-4 rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Manutenção global</h2><strong className={data.maintenance.enabled?'text-red-700':'text-green-700'}>{data.maintenance.enabled?'Sistema bloqueado':'Sistema disponível'}</strong><Button variant="outline" disabled={pending} onClick={()=>void load().catch(e=>setError(e.message))}>Atualizar</Button></div>
    <p className="text-sm text-muted-foreground">Bloqueia as operações de todas as lojas. A administração global mantém acesso para liberar o sistema. Dispositivos desconectados recebem a alteração ao reconectar; bloqueios já recebidos permanecem ativos offline.</p>
    <label className="block text-sm">Mensagem exibida aos clientes<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000} minLength={5} className="mt-1 min-h-24 w-full rounded border p-3" disabled={pending}/></label>
    <label className="block text-sm">Previsão de retorno (horário de Brasília, opcional)<Input type="datetime-local" value={returnAt} onChange={e=>setReturnAt(e.target.value)} disabled={pending}/></label><p className="text-xs text-muted-foreground">A previsão é informativa. A liberação é feita manualmente neste painel.</p>
    <label className="block text-sm">Motivo para a auditoria<Input value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} minLength={5} disabled={pending}/></label>
    <div className="flex flex-wrap gap-3"><Button variant={data.maintenance.enabled?'default':'destructive'} disabled={pending||message.trim().length<5||reason.trim().length<5} onClick={()=>setConfirm(!data.maintenance.enabled)}>{data.maintenance.enabled?'Liberar sistema':'Ativar manutenção global'}</Button>{data.maintenance.enabled&&<Button variant="outline" disabled={pending||reason.trim().length<5||message.trim().length<5} onClick={()=>setConfirm(true)}>Atualizar mensagem</Button>}</div>
   </section>
   <section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Avisos e notas de atualização</h2><form className="space-y-3" onSubmit={async e=>{e.preventDefault();if(await run(()=>savePlatformMessageAction({...draft,publish}),publish?'Comunicado publicado para todas as empresas.':'Rascunho salvo.')){setDraft(empty);setPublish(false);}}}>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Tipo<select className="mt-1 w-full rounded border p-2" value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as 'notice'|'patchnotes'})} disabled={pending}><option value="notice">Aviso</option><option value="patchnotes">Notas de atualização</option></select></label><label className="text-sm">Versão (opcional)<Input value={draft.version} maxLength={40} onChange={e=>setDraft({...draft,version:e.target.value})} disabled={pending}/></label></div>
    <label className="block text-sm">Título<Input required minLength={3} maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} disabled={pending}/></label>
    <label className="block text-sm">Conteúdo<textarea required minLength={5} maxLength={10000} className="mt-1 min-h-40 w-full rounded border p-3" placeholder="Descreva as novidades, correções e orientações. Use uma linha por item." value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} disabled={pending}/></label>
    <label className="flex gap-2 text-sm"><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)} disabled={pending}/>Publicar agora para todas as empresas</label>
    <div className="flex gap-3"><Button disabled={pending} type="submit">{publish?'Publicar comunicado':'Salvar rascunho'}</Button>{draft.id&&<Button type="button" variant="outline" onClick={()=>{setDraft(empty);setPublish(false);}}>Cancelar edição</Button>}</div>
   </form></section>
   <section className="space-y-3"><h2 className="font-semibold">Histórico de comunicados</h2>{!data.messages.length&&<p className="text-sm">Nenhum comunicado cadastrado.</p>}{data.messages.map(item=><article className="rounded-xl border bg-white p-4" key={item.id}><p className="text-xs text-muted-foreground">{item.archived?'Arquivado':item.publishedAt?'Publicado em '+new Date(item.publishedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Rascunho'} · {item.kind==='patchnotes'?'Notas de atualização':'Aviso'} {item.version}</p><h3 className="mt-2 font-semibold">{item.title}</h3><p className="my-3 whitespace-pre-wrap break-words text-sm">{item.body}</p>{!item.archived&&<div className="flex gap-3">{!item.publishedAt&&<Button size="sm" variant="outline" disabled={pending} onClick={()=>{setDraft({id:item.id,kind:item.kind,title:item.title,body:item.body,version:item.version});setPublish(false);}}>Editar / publicar</Button>}<Button size="sm" variant="outline" disabled={pending} onClick={()=>void run(()=>archivePlatformMessageAction(item.id),'Comunicado arquivado.')}>Arquivar</Button></div>}</article>)}</section>
  </>}
  <Dialog open={confirm!==null} onOpenChange={v=>{if(!v&&!pending)setConfirm(null);}}><DialogContent><DialogHeader><DialogTitle>{confirm?'Ativar ou atualizar manutenção global':'Liberar todas as lojas'}</DialogTitle><DialogDescription>{confirm?'As lojas conectadas terão as operações bloqueadas. Pendências locais serão preservadas para envio após a liberação.':'O sistema voltará a aceitar operações e sincronizar pendências.'}</DialogDescription></DialogHeader><p className="whitespace-pre-wrap text-sm">{message}</p><div className="flex justify-end gap-3"><Button variant="outline" disabled={pending} onClick={()=>setConfirm(null)}>Cancelar</Button><Button variant={confirm?'destructive':'default'} disabled={pending} onClick={async()=>{if(!data||confirm===null)return;const enabled=confirm;if(await run(()=>saveMaintenanceAction({enabled,message,expectedReturn:returnAt?new Date(returnAt+':00-03:00').toISOString():null,revision:data.maintenance.revision,reason}),enabled?'Manutenção global ativada.':'Sistema liberado.')){setConfirm(null);setReason('');}}}>Confirmar</Button></div></DialogContent></Dialog>
 </div>;
}
